// Code generated by mockery v2.53.3. DO NOT EDIT.

package _mock

import mock "github.com/stretchr/testify/mock"

// LogShowWriter is an autogenerated mock type for the LogShowWriter type
type LogShowWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: p
func (_m *LogShowWriter) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLogShowWriter creates a new instance of LogShowWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogShowWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogShowWriter {
	mock := &LogShowWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
