project_name: bank-reconcile

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org

dist: dist

before:
  hooks:
    - go mod tidy

git:
  enable: true
  tag_sort: semver

builds:
  - id: bank-reconcile
    binary: bank-reconcile
    ldflags:
      - -s -w
      - -X bank-reconcile/variable.GitCommit={{ .ShortCommit }}
      - -X bank-reconcile/variable.Version={{ .Version }}
      - -X bank-reconcile/variable.Environment=default
      - -X bank-reconcile/variable.BuildDate={{ .Date }}
      - -X bank-reconcile/variable.TimeZone=Asia/Jakarta
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: bank-reconcile-windows-amd64
    builds: [bank-reconcile]
    goos: windows
    goarch: amd64
    format: zip
    name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

  - id: bank-reconcile-darwin-arm64
    builds: [bank-reconcile]
    goos: darwin
    goarch: arm64
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

  - id: bank-reconcile-darwin-amd64
    builds: [bank-reconcile]
    goos: darwin
    goarch: amd64
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

  - id: bank-reconcile-linux-arm64
    builds: [bank-reconcile]
    goos: linux
    goarch: arm64
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

  - id: bank-reconcile-linux-amd64
    builds: [bank-reconcile]
    goos: linux
    goarch: amd64
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

release:
  draft: false

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
