version: 2

project_name: bank-reconcile

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org

dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: bank-reconcile-windows-amd64
    binary: bank-reconcile
    ldflags:
      - -s -w
      - -X github.com/oprekable/bank-reconcile/variable.GitCommit={{ .ShortCommit }}
      - -X github.com/oprekable/bank-reconcile/variable.Version={{ .Version }}
      - -X github.com/oprekable/bank-reconcile/variable.Environment=default
      - -X github.com/oprekable/bank-reconcile/variable.BuildDate={{ .Date }}
      - -X github.com/oprekable/bank-reconcile/variable.TimeZone=Asia/Jakarta
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64]

  - id: bank-reconcile-darwin-arm64
    binary: bank-reconcile
    ldflags:
      - -s -w
      - -X github.com/oprekable/bank-reconcile/variable.GitCommit={{ .ShortCommit }}
      - -X github.com/oprekable/bank-reconcile/variable.Version={{ .Version }}
      - -X github.com/oprekable/bank-reconcile/variable.Environment=default
      - -X github.com/oprekable/bank-reconcile/variable.BuildDate={{ .Date }}
      - -X github.com/oprekable/bank-reconcile/variable.TimeZone=Asia/Jakarta
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos: [darwin]
    goarch: [arm64]

  - id: bank-reconcile-darwin-amd64
    binary: bank-reconcile
    ldflags:
      - -s -w
      - -X github.com/oprekable/bank-reconcile/variable.GitCommit={{ .ShortCommit }}
      - -X github.com/oprekable/bank-reconcile/variable.Version={{ .Version }}
      - -X github.com/oprekable/bank-reconcile/variable.Environment=default
      - -X github.com/oprekable/bank-reconcile/variable.BuildDate={{ .Date }}
      - -X github.com/oprekable/bank-reconcile/variable.TimeZone=Asia/Jakarta
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos: [darwin]
    goarch: [amd64]

  - id: bank-reconcile-linux-arm64
    binary: bank-reconcile
    ldflags:
      - -s -w
      - -X github.com/oprekable/bank-reconcile/variable.GitCommit={{ .ShortCommit }}
      - -X github.com/oprekable/bank-reconcile/variable.Version={{ .Version }}
      - -X github.com/oprekable/bank-reconcile/variable.Environment=default
      - -X github.com/oprekable/bank-reconcile/variable.BuildDate={{ .Date }}
      - -X github.com/oprekable/bank-reconcile/variable.TimeZone=Asia/Jakarta
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [arm64]

  - id: bank-reconcile-linux-amd64
    binary: bank-reconcile
    ldflags:
      - -s -w
      - -X github.com/oprekable/bank-reconcile/variable.GitCommit={{ .ShortCommit }}
      - -X github.com/oprekable/bank-reconcile/variable.Version={{ .Version }}
      - -X github.com/oprekable/bank-reconcile/variable.Environment=default
      - -X github.com/oprekable/bank-reconcile/variable.BuildDate={{ .Date }}
      - -X github.com/oprekable/bank-reconcile/variable.TimeZone=Asia/Jakarta
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64]

archives:
  - id: bank-reconcile-windows-amd64
    ids: [bank-reconcile-windows-amd64]
    formats: [ 'zip' ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

  - id: bank-reconcile-darwin-arm64
    ids: [bank-reconcile-darwin-arm64]
    formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

  - id: bank-reconcile-darwin-amd64
    ids: [bank-reconcile-darwin-amd64]
    formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

  - id: bank-reconcile-linux-arm64
    ids: [bank-reconcile-linux-arm64]
    formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

  - id: bank-reconcile-linux-amd64
    ids: [bank-reconcile-linux-amd64]
    formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: params/*.toml
        dst: params
        strip_parent: true
      - src: params/*.env
        dst: params
        strip_parent: true

release:
  draft: false

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
