packages:
  github.com/oprekable/bank-reconcile:
    config:
      recursive: True
      with-expecter: False
      inpackage: False
      dir: "{{.InterfaceDir}}/_mock"
      mockname: "{{.InterfaceName}}"
      outpkg: "_mock"
      filename: "{{.InterfaceName}}.go"
      all: True
