// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"context"
	"embed"
	"github.com/oprekable/bank-reconcile/internal/app/appcontext"
	"github.com/oprekable/bank-reconcile/internal/app/component"
	"github.com/oprekable/bank-reconcile/internal/app/component/cconfig"
	"github.com/oprekable/bank-reconcile/internal/app/component/cerror"
	"github.com/oprekable/bank-reconcile/internal/app/component/cfs"
	"github.com/oprekable/bank-reconcile/internal/app/component/clogger"
	"github.com/oprekable/bank-reconcile/internal/app/component/cprofiler"
	"github.com/oprekable/bank-reconcile/internal/app/component/csqlite"
	"github.com/oprekable/bank-reconcile/internal/app/err/core"
	"github.com/oprekable/bank-reconcile/internal/app/handler/hcli"
	"github.com/oprekable/bank-reconcile/internal/app/repository"
	"github.com/oprekable/bank-reconcile/internal/app/repository/process"
	"github.com/oprekable/bank-reconcile/internal/app/repository/sample"
	"github.com/oprekable/bank-reconcile/internal/app/server"
	"github.com/oprekable/bank-reconcile/internal/app/server/cli"
	"github.com/oprekable/bank-reconcile/internal/app/service"
	process2 "github.com/oprekable/bank-reconcile/internal/app/service/process"
	sample2 "github.com/oprekable/bank-reconcile/internal/app/service/sample"
	"github.com/spf13/afero"
	"io"
	"os"
)

// Injectors from inject.go:

func WireApp(ctx context.Context, embedFS *embed.FS, appName cconfig.AppName, tz cconfig.TimeZone, errType []core.ErrorType, isShowLog clogger.IsShowLog, dBPath csqlite.DBPath) (*appcontext.AppContext, func(), error) {
	fs := _wireFsValue
	configPaths := _wireConfigPathsValue
	config, err := cconfig.NewConfig(ctx, embedFS, fs, configPaths, appName, tz)
	if err != nil {
		return nil, nil, err
	}
	logShowWriter := _wireFileValue
	logNoShowWriter := _wireWriterValue
	logger := clogger.ProviderLogger(ctx, isShowLog, logShowWriter, logNoShowWriter)
	erType := cerror.ProvideErType(errType)
	cerrorError := cerror.NewError(erType)
	dbSqlite, cleanup, err := csqlite.ProviderDBSqlite(config, logger, dBPath)
	if err != nil {
		return nil, nil, err
	}
	cfsFs := cfs.ProviderCFs(fs)
	profiler := cprofiler.NewProfiler(logger)
	components := component.NewComponents(ctx, config, logger, cerrorError, dbSqlite, cfsFs, profiler)
	db, err := sample.ProviderDB(components)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	processDB, err := process.ProviderDB(components)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repositories := repository.NewRepositories(db, processDB)
	svc := sample2.ProviderSvc(components, repositories)
	processSvc := process2.ProviderSvc(components, repositories)
	services := service.NewServices(svc, processSvc)
	v := hcli.ProviderHandlers()
	cliCli, err := cli.NewCli(components, services, repositories, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serverServer := server.NewServer(cliCli)
	appContext, cleanup2 := appcontext.NewAppContext(ctx, embedFS, repositories, services, components, serverServer)
	return appContext, func() {
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireFsValue          = afero.NewOsFs()
	_wireConfigPathsValue = cconfig.ConfigPaths([]string{
		"./*.toml",
		"./params/*.toml",
	})
	_wireFileValue   = os.Stdout
	_wireWriterValue = io.Discard
)

// inject.go:

type Fn func(ctx context.Context, embedFS *embed.FS, appName cconfig.AppName, tz cconfig.TimeZone, errType []core.ErrorType, isShowLog clogger.IsShowLog, dBPath csqlite.DBPath) (*appcontext.AppContext, func(), error)

var WireAppFn Fn = WireApp
