// Code generated by mockery v2.53.3. DO NOT EDIT.

package _mock

import mock "github.com/stretchr/testify/mock"

// IRunner is an autogenerated mock type for the IRunner type
type IRunner struct {
	mock.Mock
}

// Run provides a mock function with no fields
func (_m *IRunner) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIRunner creates a new instance of IRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRunner {
	mock := &IRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
