// Code generated by mockery v2.53.5. DO NOT EDIT.

package _mock

import (
	context "context"

	afero "github.com/spf13/afero"

	mock "github.com/stretchr/testify/mock"

	process "github.com/oprekable/bank-reconcile/internal/app/service/process"

	progressbar "github.com/schollz/progressbar/v3"
)

// ServiceGenerator is an autogenerated mock type for the ServiceGenerator type
type ServiceGenerator struct {
	mock.Mock
}

// GenerateReconciliation provides a mock function with given fields: ctx, fs, bar
func (_m *ServiceGenerator) GenerateReconciliation(ctx context.Context, fs afero.Fs, bar *progressbar.ProgressBar) (process.ReconciliationSummary, error) {
	ret := _m.Called(ctx, fs, bar)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReconciliation")
	}

	var r0 process.ReconciliationSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, afero.Fs, *progressbar.ProgressBar) (process.ReconciliationSummary, error)); ok {
		return rf(ctx, fs, bar)
	}
	if rf, ok := ret.Get(0).(func(context.Context, afero.Fs, *progressbar.ProgressBar) process.ReconciliationSummary); ok {
		r0 = rf(ctx, fs, bar)
	} else {
		r0 = ret.Get(0).(process.ReconciliationSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, afero.Fs, *progressbar.ProgressBar) error); ok {
		r1 = rf(ctx, fs, bar)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceGenerator creates a new instance of ServiceGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceGenerator {
	mock := &ServiceGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
