name: Performance Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.7
          cache: true

      - name: Run benchmarks
        run: |
          go test -bench=. -benchmem -count=5 -timeout=30m ./... > benchmark-results.txt  

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: benchmark-results.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-threshold: '200%'
          fail-on-alert: true

      - name: Memory profiling test
        run: |
          go test -memprofile=mem.prof -cpuprofile=cpu.prof -bench=. ./...  
          go tool pprof -top mem.prof > memory-profile.txt  
          go tool pprof -top cpu.prof > cpu-profile.txt  

      - name: Upload profiling results
        uses: actions/upload-artifact@v4
        with:
          name: performance-profiles
          path: |
            memory-profile.txt  
            cpu-profile.txt  
            *.prof