name: Matrix Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.24.7]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: make install-tools

      - name: Run tests
        run: |
          go test -v -race -coverprofile=coverage.out ./...  
          go tool cover -html=coverage.out -o coverage.html  

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          flags: ${{ matrix.os }}-go${{ matrix.go-version }}
          name: codecov-${{ matrix.os }}-go${{ matrix.go-version }}